# Check if any links are broken
name: Check links

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 8 * *"


jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: lycheeverse/lychee-action@v1.2.0
        with:
          fail: true
