# Check if any links are broken
name: Check links

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"


jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
