name: Create website
on: [push, pull_request]

jobs:
  create_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      # Install plantuml
      - name: Install OS package dependencies
        run: |
          sudo apt update
          sudo apt install plantuml
          #sudo apt install npm
          #npm install mermaid
          npm install -g @mermaid-js/mermaid-cli
          #npm install markmap

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: remove unused folders
        run: |
          rm -rf docs/*/not_used
          rm -rf docs/*/may2024
          rm -rf docs/*/May23
          rm -rf docs/feb23_course
          rm -rf docs/may2024
          rm -rf docs/May23
          rm -rf docs/May_24

      - name: Sphinx build
        run: |
          sphinx-build docs _build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

      - name: Install linter
        run: pip install sphinx-lint

      - name: Run linter, will never give an error
        run: sphinx-lint docs || true

